Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  # Network configuration
  config.vm.network "forwarded_port", guest: 3000, host: 3000 # Grafana
  config.vm.network "forwarded_port", guest: 8080, host: 8080 # App Frontend (Example)
  config.vm.network "forwarded_port", guest: 8000, host: 8000 # App Backend (Example)
  config.vm.network "forwarded_port", guest: 8200, host: 8200 # Vault
  config.vm.network "forwarded_port", guest: 9090, host: 9090 # Prometheus

  # Shared folders
  config.vm.synced_folder "../", "/home/vagrant/ft_transcendence"

  # VM Resources
  config.vm.provider "virtualbox" do |vb|
    vb.gui = true 
    vb.memory = "2048"
    vb.cpus = 2
    vb.name = "ft_transcendence_dev"
  end

  # Provisioning with Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.become = true
  end
end
